language: elixir
elixir:
  - 1.5.2
notifications:
  recipients:
    - travis@jeffweiss.org
    - matt@mattrobinson.net
otp_release:
  - 20.0
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, test"
